package dev.javelin.compiler;

import com.sun.source.tree.*;
import com.sun.source.util.JavacTask;
import com.sun.source.util.SourcePositions;
import com.sun.source.util.TreePath;
import com.sun.source.util.TreePathScanner;
import com.sun.source.util.Trees;

import javax.lang.model.element.ExecutableElement;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.element.Element;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.Types;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Collectors;

final class JavaScriptEmitter {
    private static final Set<String> RUNTIME_NAMES = Set.of(
            "div", "span", "h1", "h2", "p", "button", "form", "input", "textarea", "select", "option", "label", "ul", "li", "a", "img", "tag",
            "fragment", "text", "component", "portal", "lazy", "each", "when", "key", "className", "tw", "twWhen", "id", "value", "checked",
            "selected", "disabled", "required", "multiple", "placeholder", "href", "src", "alt", "title", "role", "tabIndex", "name", "type", "forId", "aria", "data", "attr",
            "style", "onClick", "onInput", "onChange", "onSubmit", "eventValue", "eventChecked", "ref", "route", "routeGroup", "guard", "redirect", "router", "navigate", "link", "formValid", "modal", "spinner",
            "cssModule", "context");
    private static final Set<String> COMPONENT_METHODS = Set.of("props", "children", "state", "resource", "resourceOptions", "field", "effect", "onMount", "onUnmount", "provideContext", "useContext");

    private final JavacTask task;
    private final Trees trees;
    private final Types types;
    private final TypeMirror componentType;
    private final SourcePositions positions;
    private final List<CompilationUnitTree> units;
    private final String runtimePath;
    private final String moduleSuffix;
    private final Map<String, RecordModel> records = new LinkedHashMap<>();
    private final Map<String, ClassModel> components = new LinkedHashMap<>();
    private final Map<String, List<String>> enums = new LinkedHashMap<>();
    private final Set<String> usedRuntime = new TreeSet<>();
    private final Map<String, String> lazyChunks = new LinkedHashMap<>();
    private CompilationUnitTree currentUnit;
    private ClassModel currentClass;
    private Set<String> locals = Set.of();

    JavaScriptEmitter(JavacTask task, List<CompilationUnitTree> units, String runtimePath, String moduleSuffix) {
        this.task = task;
        this.trees = Trees.instance(task);
        this.types = task.getTypes();
        TypeElement componentElement = task.getElements().getTypeElement("javelin.ui.Component");
        if (componentElement == null) throw new IllegalStateException("javelin.ui.Component is unavailable on the compiler classpath");
        this.componentType = types.erasure(componentElement.asType());
        this.positions = trees.getSourcePositions();
        this.units = units;
        this.runtimePath = runtimePath;
        this.moduleSuffix = moduleSuffix;
    }

    String emit() {
        collectModels();
        resolveInheritance();
        List<ClassModel> roots = components.values().stream().filter(model -> model.selector != null).toList();
        if (roots.size() != 1) throw error(null, "Expected exactly one @App component, found " + roots.size());
        ClassModel root = roots.get(0);
        validateSplitDependencies(root);

        List<String> sharedNames = new ArrayList<>();
        sharedNames.addAll(records.keySet());
        sharedNames.addAll(enums.keySet());
        components.values().stream().filter(component -> component != root).forEach(component -> sharedNames.add(component.name));
        if (!sharedNames.isEmpty()) lazyChunks.put("javelin.shared.mjs", emitSharedModule(root, sharedNames));
        components.values().stream().filter(component -> component.lazy)
                .forEach(component -> lazyChunks.put(component.name + ".lazy.mjs", emitLazyChunk(component, sharedNames)));

        // Emit the application root last so its exact runtime imports and source markers are preserved.
        String rootDeclaration = emitComponent(root);

        String imports = usedRuntime.isEmpty() ? "" : ", " + String.join(", ", usedRuntime);
        return "// Generated by the Javelin javac AST compiler. Do not edit.\n" +
                "import { Component, mount" + imports + " } from " + quote(runtimePath) + ";\n\n" +
                (sharedNames.isEmpty() ? "" : "import { " + String.join(", ", sharedNames) + " } from " + quote("./javelin.shared.mjs" + moduleSuffix) + ";\n\n") +
                rootDeclaration + "\n\n" +
                "mount(" + root.name + ", " + quote(root.selector) + ");\n";
    }

    Map<String, String> lazyChunks() {
        return Map.copyOf(lazyChunks);
    }

    private String emitSharedModule(ClassModel root, List<String> sharedNames) {
        List<String> declarations = new ArrayList<>();
        records.values().forEach(record -> declarations.add(emitRecord(record)));
        enums.forEach((name, constants) -> declarations.add(emitEnum(name, constants)));
        orderedComponents().stream().filter(component -> component != root && !component.lazy)
                .forEach(component -> declarations.add(emitComponent(component)));
        components.values().stream().filter(component -> component.lazy).forEach(component -> {
            usedRuntime.add("lazy");
            declarations.add("const " + component.name + " = lazy(() => import(" + quote("./" + component.name + ".lazy.mjs" + moduleSuffix) +
                    ").then((module) => module.default));");
        });
        return runtimeImport("// Generated shared component chunk. Do not edit.\n") +
                String.join("\n\n", declarations) + "\n\nexport { " + String.join(", ", sharedNames) + " };\n";
    }

    private String emitLazyChunk(ClassModel component, List<String> sharedNames) {
        List<String> declarations = new ArrayList<>();
        declarations.add(emitComponent(component));
        List<String> imports = sharedNames.stream().filter(name -> !name.equals(component.name)).toList();
        String sharedImport = imports.isEmpty() ? "" : "import { " + String.join(", ", imports) + " } from " + quote("./javelin.shared.mjs" + moduleSuffix) + ";\n\n";
        return runtimeImport("// Generated lazy component chunk. Do not edit.\n") + sharedImport +
                String.join("\n\n", declarations) + "\n\nexport default " + component.name + ";\n";
    }

    private String runtimeImport(String header) {
        Set<String> imports = new TreeSet<>(RUNTIME_NAMES);
        imports.addAll(Set.of("newJavaArray", "numericValue", "castByte", "castShort", "castChar", "castInt", "castFloat"));
        return header + "import { Component, " + String.join(", ", imports) + " } from " + quote(runtimePath) + ";\n\n";
    }

    private void collectModels() {
        for (CompilationUnitTree unit : units) {
            currentUnit = unit;
            for (Tree declaration : unit.getTypeDecls()) {
                if (!(declaration instanceof ClassTree type)) continue;
                if (type.getKind() == Tree.Kind.RECORD) collectRecord(unit, type);
                else if (type.getKind() == Tree.Kind.ENUM) collectEnum(type);
                else if (isComponent(unit, type)) collectComponent(unit, type);
            }
        }
    }

    private void collectRecord(CompilationUnitTree unit, ClassTree type) {
        type.getMembers().stream().filter(MethodTree.class::isInstance).map(MethodTree.class::cast)
                .filter(method -> positions.getEndPosition(unit, method) >= 0).findFirst().ifPresent(method -> {
                    throw error(method, "Custom record constructors and methods are not supported yet");
                });
        List<String> fields = type.getMembers().stream().filter(VariableTree.class::isInstance)
                .map(VariableTree.class::cast)
                .filter(variable -> !variable.getModifiers().getFlags().contains(javax.lang.model.element.Modifier.STATIC))
                .map(variable -> variable.getName().toString()).toList();
        String name = type.getSimpleName().toString();
        if (records.putIfAbsent(name, new RecordModel(name, fields, unit, type)) != null) {
            throw error(type, "Duplicate record simple name '" + name + "' is not supported; use unique names across packages");
        }
    }

    private void collectEnum(ClassTree type) {
        List<String> constants = type.getMembers().stream()
                .filter(member -> member instanceof VariableTree variable && variable.getInitializer() instanceof NewClassTree)
                .map(member -> ((VariableTree) member).getName().toString()).toList();
        String name = type.getSimpleName().toString();
        if (enums.putIfAbsent(name, constants) != null) throw error(type, "Duplicate enum simple name '" + name + "' is not supported");
    }

    private void collectComponent(CompilationUnitTree unit, ClassTree type) {
        String name = type.getSimpleName().toString();
        TypeElement element = (TypeElement) trees.getElement(TreePath.getPath(unit, type));
        if (element == null) throw error(type, "Unable to resolve component type");
        TypeMirror superclass = types.erasure(element.getSuperclass());
        String superName = "Component";
        if (!types.isSameType(superclass, componentType)) {
            Element parent = types.asElement(superclass);
            if (!(parent instanceof TypeElement parentType) || !types.isSubtype(superclass, componentType)) {
                throw error(type, "Component superclass could not be resolved");
            }
            superName = parentType.getSimpleName().toString();
        }
        List<MethodTree> declaredMethods = type.getMembers().stream().filter(MethodTree.class::isInstance)
                .map(MethodTree.class::cast).toList();
        declaredMethods.stream().filter(method -> method.getName().contentEquals("<init>") && positions.getEndPosition(unit, method) >= 0)
                .findFirst().ifPresent(method -> { throw error(method, "Explicit component constructors are not supported; use field initializers and lifecycle methods"); });
        Map<String, Long> methodCounts = declaredMethods.stream().filter(method -> !method.getName().contentEquals("<init>"))
                .collect(Collectors.groupingBy(method -> method.getName().toString(), LinkedHashMap::new, Collectors.counting()));
        methodCounts.entrySet().stream().filter(entry -> entry.getValue() > 1).findFirst().ifPresent(entry -> {
            throw error(type, "Method overloading is not supported yet: '" + entry.getKey() + "'");
        });
        String selector = annotationString(type.getModifiers(), "App");
        boolean lazy = hasAnnotation(type.getModifiers(), "Lazy");
        if (lazy && selector != null) throw error(type, "@App and @Lazy cannot be used on the same component");
        Set<String> fields = type.getMembers().stream().filter(VariableTree.class::isInstance)
                .map(VariableTree.class::cast).map(variable -> variable.getName().toString()).collect(Collectors.toCollection(LinkedHashSet::new));
        Set<String> staticFields = type.getMembers().stream().filter(VariableTree.class::isInstance)
                .map(VariableTree.class::cast)
                .filter(variable -> variable.getModifiers().getFlags().contains(javax.lang.model.element.Modifier.STATIC))
                .map(variable -> variable.getName().toString()).collect(Collectors.toCollection(LinkedHashSet::new));
        Set<String> methods = type.getMembers().stream().filter(MethodTree.class::isInstance)
                .map(MethodTree.class::cast).map(method -> method.getName().toString()).filter(method -> !method.equals("<init>"))
                .collect(Collectors.toCollection(LinkedHashSet::new));
        Set<String> staticMethods = declaredMethods.stream().filter(method -> method.getModifiers().getFlags().contains(Modifier.STATIC))
                .map(method -> method.getName().toString()).collect(Collectors.toCollection(LinkedHashSet::new));
        ClassModel model = new ClassModel(name, element.getQualifiedName().toString(), superName, selector, lazy, fields, staticFields, methods, staticMethods, unit, type);
        if (components.putIfAbsent(name, model) != null) {
            throw error(type, "Duplicate component simple name '" + name + "' is not supported; use unique names across packages");
        }
    }

    private void resolveInheritance() {
        Set<String> resolved = new HashSet<>();
        Set<String> visiting = new HashSet<>();
        for (ClassModel model : components.values()) resolveInheritance(model, resolved, visiting);
    }

    private void validateSplitDependencies(ClassModel root) {
        components.values().stream().filter(model -> model != root).forEach(model -> {
            if (referencesComponent(model, root)) {
                currentUnit = model.unit;
                throw error(model.tree, "Component '" + model.name + "' cannot reference the @App root component '" + root.name + "'");
            }
            if (model.lazy && !model.superName.equals("Component") && components.get(model.superName).lazy) {
                currentUnit = model.unit;
                throw error(model.tree, "@Lazy component cannot extend another @Lazy component; use composition instead");
            }
        });
    }

    private boolean referencesComponent(ClassModel model, ClassModel target) {
        boolean[] found = { false };
        new TreePathScanner<Void, Void>() {
            @Override public Void visitIdentifier(IdentifierTree tree, Void unused) {
                Element element = trees.getElement(getCurrentPath());
                if (element instanceof TypeElement type && type.getQualifiedName().contentEquals(target.qualifiedName)) found[0] = true;
                return super.visitIdentifier(tree, unused);
            }
        }.scan(TreePath.getPath(model.unit, model.tree), null);
        return found[0];
    }

    private void resolveInheritance(ClassModel model, Set<String> resolved, Set<String> visiting) {
        if (resolved.contains(model.name)) return;
        if (!visiting.add(model.name)) throw error(model.tree, "Circular component inheritance involving '" + model.name + "'");
        if (!model.superName.equals("Component")) {
            ClassModel parent = components.get(model.superName);
            if (parent == null) throw error(model.tree, "Component superclass '" + model.superName + "' must be part of the compiled Java sources");
            resolveInheritance(parent, resolved, visiting);
            model.fields.addAll(parent.fields);
            model.staticFields.addAll(parent.staticFields);
            model.methods.addAll(parent.methods);
            model.staticMethods.addAll(parent.staticMethods);
        }
        visiting.remove(model.name);
        resolved.add(model.name);
    }

    private List<ClassModel> orderedComponents() {
        List<ClassModel> ordered = new ArrayList<>();
        Set<String> added = new HashSet<>();
        for (ClassModel model : components.values()) addComponentInOrder(model, ordered, added);
        return ordered;
    }

    private void addComponentInOrder(ClassModel model, List<ClassModel> ordered, Set<String> added) {
        if (added.contains(model.name)) return;
        if (!model.superName.equals("Component")) addComponentInOrder(components.get(model.superName), ordered, added);
        added.add(model.name);
        ordered.add(model);
    }

    private boolean isComponent(CompilationUnitTree unit, ClassTree type) {
        Element element = trees.getElement(TreePath.getPath(unit, type));
        return element instanceof TypeElement typeElement && types.isSubtype(types.erasure(typeElement.asType()), componentType)
                && !types.isSameType(types.erasure(typeElement.asType()), componentType);
    }

    private String emitRecord(RecordModel record) {
        sourceMarker(record.unit, record.tree);
        return marker(record.unit, record.tree) + "\nclass " + record.name + " {\n  constructor(" + String.join(", ", record.fields) + ") {\n" +
                record.fields.stream().map(field -> "    this." + field + " = " + field + ";").collect(Collectors.joining("\n")) +
                "\n  }\n}";
    }

    private String emitEnum(String name, List<String> constants) {
        return "const " + name + " = Object.freeze({ " + constants.stream()
                .map(value -> value + ": " + quote(value)).collect(Collectors.joining(", ")) + " });";
    }

    private String emitComponent(ClassModel model) {
        currentUnit = model.unit;
        currentClass = model;
        List<VariableTree> fields = model.tree.getMembers().stream().filter(VariableTree.class::isInstance)
                .map(VariableTree.class::cast).toList();
        List<MethodTree> methods = model.tree.getMembers().stream().filter(MethodTree.class::isInstance)
                .map(MethodTree.class::cast).filter(method -> !method.getName().contentEquals("<init>") && method.getBody() != null).toList();
        StringBuilder output = new StringBuilder(marker(model.unit, model.tree)).append("\nclass ").append(model.name).append(" extends ").append(model.superName).append(" {\n")
                .append("  constructor(props) {\n    super(props);\n");
        for (VariableTree field : fields) {
            if (field.getInitializer() == null) throw error(field, "Component fields require an initializer");
            output.append("    ").append(marker(model.unit, field)).append("\n");
            if (isState(field)) output.append("    this.").append(field.getName()).append(" = ").append(expression(field.getInitializer())).append(";\n");
            else if (field.getModifiers().getFlags().contains(javax.lang.model.element.Modifier.STATIC)) {
                // Static fields are emitted after the class.
            } else output.append("    this.").append(field.getName()).append(" = ").append(expression(field.getInitializer())).append(";\n");
        }
        output.append("  }\n");
        for (MethodTree method : methods) output.append("\n").append(emitMethod(method));
        output.append("}\n");
        for (VariableTree field : fields) {
            if (field.getModifiers().getFlags().contains(javax.lang.model.element.Modifier.STATIC)) {
                output.append(model.name).append(".").append(field.getName()).append(" = ").append(expression(field.getInitializer())).append(";\n");
            }
        }
        return output.toString().stripTrailing();
    }

    private boolean isState(VariableTree field) {
        return field.getType().toString().startsWith("State<") || field.getType().toString().equals("State");
    }

    private String emitMethod(MethodTree method) {
        locals = method.getParameters().stream().map(parameter -> parameter.getName().toString())
                .collect(Collectors.toCollection(LinkedHashSet::new));
        String parameters = String.join(", ", locals);
        String name = method.getName().toString();
        String body = statement(method.getBody(), 1);
        locals = Set.of();
        String staticPrefix = method.getModifiers().getFlags().contains(Modifier.STATIC) ? "static " : "";
        return "  " + marker(currentUnit, method) + "\n  " + staticPrefix + name + "(" + parameters + ") " + body + "\n";
    }

    private String statement(StatementTree tree, int indent) {
        if (tree == null) return "{}";
        String pad = "  ".repeat(indent);
        if (tree instanceof BlockTree block) {
            Set<String> previousLocals = locals;
            locals = new LinkedHashSet<>(locals);
            String content = block.getStatements().stream().map(item -> pad + "  " + marker(currentUnit, item) + "\n" + pad + "  " + statement(item, indent + 1))
                    .collect(Collectors.joining("\n"));
            locals = previousLocals;
            return "{" + (content.isEmpty() ? "" : "\n" + content + "\n" + pad) + "}";
        }
        if (tree instanceof ReturnTree value) return "return " + expression(value.getExpression()) + ";";
        if (tree instanceof ExpressionStatementTree value) return expression(value.getExpression()) + ";";
        if (tree instanceof VariableTree variable) {
            locals = new LinkedHashSet<>(locals);
            locals.add(variable.getName().toString());
            return "let " + variable.getName() + (variable.getInitializer() == null ? "" : " = " + expression(variable.getInitializer())) + ";";
        }
        if (tree instanceof IfTree value) {
            String result = "if (" + expression(value.getCondition()) + ") " + statement(value.getThenStatement(), indent);
            return value.getElseStatement() == null ? result : result + " else " + statement(value.getElseStatement(), indent);
        }
        if (tree instanceof EnhancedForLoopTree value) {
            Set<String> previousLocals = locals;
            locals = new LinkedHashSet<>(locals);
            locals.add(value.getVariable().getName().toString());
            String result = "for (const " + value.getVariable().getName() + " of " + expression(value.getExpression()) + ") " + statement(value.getStatement(), indent);
            locals = previousLocals;
            return result;
        }
        if (tree instanceof WhileLoopTree value) return "while (" + expression(value.getCondition()) + ") " + statement(value.getStatement(), indent);
        if (tree instanceof DoWhileLoopTree value) return "do " + statement(value.getStatement(), indent) + " while (" + expression(value.getCondition()) + ");";
        if (tree instanceof BreakTree) return "break;";
        if (tree instanceof ContinueTree) return "continue;";
        if (tree instanceof ThrowTree value) return "throw " + expression(value.getExpression()) + ";";
        if (tree instanceof ForLoopTree value) {
            Set<String> previousLocals = locals;
            locals = new LinkedHashSet<>(locals);
            String initializers = value.getInitializer().stream().map(item -> statement(item, indent).replaceFirst(";$", "")).collect(Collectors.joining(", "));
            String updates = value.getUpdate().stream().map(item -> expression(item.getExpression())).collect(Collectors.joining(", "));
            String result = "for (" + initializers + "; " + expression(value.getCondition()) + "; " + updates + ") " + statement(value.getStatement(), indent);
            locals = previousLocals;
            return result;
        }
        throw error(tree, "Unsupported Java statement: " + tree.getKind());
    }

    private String expression(ExpressionTree tree) {
        if (tree == null) return "";
        if (tree instanceof LiteralTree literal) return literal(literal.getValue());
        if (tree instanceof IdentifierTree identifier) {
            String name = identifier.getName().toString();
            if (currentClass != null && currentClass.fields.contains(name) && !locals.contains(name)) {
                return currentClass.staticFields.contains(name) ? currentClass.name + "." + name : "this." + name;
            }
            return name;
        }
        if (tree instanceof ParenthesizedTree value) return "(" + expression(value.getExpression()) + ")";
        if (tree instanceof MemberSelectTree value) {
            if (value.getIdentifier().contentEquals("class")) return expression(value.getExpression());
            return expression(value.getExpression()) + "." + value.getIdentifier();
        }
        if (tree instanceof MethodInvocationTree call) return invocation(call);
        if (tree instanceof NewClassTree value) {
            String type = value.getIdentifier().toString();
            String resolvedType = typeName(value);
            if (Set.of("java.util.ArrayList", "java.util.LinkedList").contains(resolvedType)) {
                if (value.getArguments().isEmpty()) return "[]";
                if (value.getArguments().size() == 1 && isJavaCollectionLike(value.getArguments().get(0))) {
                    return "Array.from(" + expression(value.getArguments().get(0)) + ")";
                }
                throw error(value, "Unsupported List constructor; use no arguments or one collection");
            }
            if (Set.of("java.util.HashMap", "java.util.LinkedHashMap").contains(resolvedType)) {
                if (value.getArguments().isEmpty()) return "new Map()";
                if (value.getArguments().size() == 1 && isJavaMapLike(value.getArguments().get(0))) {
                    return "new Map(" + expression(value.getArguments().get(0)) + ")";
                }
                throw error(value, "Unsupported Map constructor; use no arguments or one map");
            }
            if (Set.of("java.util.HashSet", "java.util.LinkedHashSet").contains(resolvedType)) {
                if (value.getArguments().isEmpty()) return "new Set()";
                if (value.getArguments().size() == 1 && isJavaCollectionLike(value.getArguments().get(0))) {
                    return "new Set(" + expression(value.getArguments().get(0)) + ")";
                }
                throw error(value, "Unsupported Set constructor; use no arguments or one collection");
            }
            if (resolvedType.startsWith("java.")) throw error(value, "Unsupported Java library constructor: " + resolvedType);
            return "new " + value.getIdentifier() + "(" + expressions(value.getArguments()) + ")";
        }
        if (tree instanceof LambdaExpressionTree value) {
            String parameters = value.getParameters().stream().map(parameter -> parameter.getName().toString()).collect(Collectors.joining(", "));
            Set<String> previous = locals;
            locals = new LinkedHashSet<>(locals);
            value.getParameters().forEach(parameter -> locals.add(parameter.getName().toString()));
            String body = value.getBody() instanceof ExpressionTree expression ? expression(expression) : statement((StatementTree) value.getBody(), 0);
            locals = previous;
            return "(" + parameters + ") => " + body;
        }
        if (tree instanceof BinaryTree value) return binary(value);
        if (tree instanceof UnaryTree value) return unary(value);
        if (tree instanceof ConditionalExpressionTree value) return "(" + expression(value.getCondition()) + " ? " + expression(value.getTrueExpression()) + " : " + expression(value.getFalseExpression()) + ")";
        if (tree instanceof AssignmentTree value) return expression(value.getVariable()) + " = " + expression(value.getExpression());
        if (tree instanceof CompoundAssignmentTree value) {
            TypeMirror targetType = trees.getTypeMirror(TreePath.getPath(currentUnit, value.getVariable()));
            boolean stringAppend = targetType != null && targetType.toString().equals("java.lang.String") && value.getKind() == Tree.Kind.PLUS_ASSIGNMENT;
            if (!stringAppend && (targetType == null || targetType.getKind() != TypeKind.DOUBLE)) {
                throw error(value, "Compound assignment is only supported for double values and String +=; use an explicit expression instead");
            }
            return expression(value.getVariable()) + " " + compoundOperator(value.getKind()) + " " + expression(value.getExpression());
        }
        if (tree instanceof TypeCastTree value) return cast(value);
        if (tree instanceof ArrayAccessTree value) return expression(value.getExpression()) + "[" + expression(value.getIndex()) + "]";
        if (tree instanceof NewArrayTree value) {
            if (value.getDimensions().size() > 1) throw error(value, "Multidimensional array creation is not supported yet; initialize nested arrays explicitly");
            if (value.getDimensions().size() == 1) {
                usedRuntime.add("newJavaArray");
                TypeMirror elementType = value.getType() == null ? null : trees.getTypeMirror(TreePath.getPath(currentUnit, value.getType()));
                String defaultValue = elementType == null ? "null" : switch (elementType.getKind()) {
                    case BOOLEAN -> "false";
                    case BYTE, SHORT, INT, FLOAT, DOUBLE -> "0";
                    case CHAR -> quote("\0");
                    case LONG -> throw error(value, "Java long arrays are not supported");
                    default -> "null";
                };
                return "newJavaArray(" + expression(value.getDimensions().get(0)) + ", " + defaultValue + ")";
            }
            return "[" + expressions(value.getInitializers() == null ? List.of() : value.getInitializers()) + "]";
        }
        if (tree instanceof InstanceOfTree value) return expression(value.getExpression()) + " instanceof " + value.getType();
        throw error(tree, "Unsupported Java expression: " + tree.getKind());
    }

    private String invocation(MethodInvocationTree call) {
        String methodName;
        ExpressionTree receiver = null;
        if (call.getMethodSelect() instanceof IdentifierTree identifier) methodName = identifier.getName().toString();
        else {
            MemberSelectTree select = (MemberSelectTree) call.getMethodSelect();
            methodName = select.getIdentifier().toString();
            receiver = select.getExpression();
        }

        String owner = invocationOwner(call);
        if (owner.equals("java.util.List") && methodName.equals("of")) return "Object.freeze([" + expressions(call.getArguments()) + "])";
        if (owner.equals("java.util.Set") && methodName.equals("of")) return "new Set([" + expressions(call.getArguments()) + "])";
        if (owner.equals("java.util.Map") && methodName.equals("of")) return mapOf(call);
        if (owner.equals("java.util.Objects") && methodName.equals("equals")) return "Object.is(" + expressions(call.getArguments()) + ")";
        if (owner.equals("java.lang.String") && receiver instanceof IdentifierTree && methodName.equals("valueOf")) return "String(" + expressions(call.getArguments()) + ")";
        if (owner.equals("java.lang.Integer") && methodName.equals("parseInt")) {
            if (call.getArguments().size() < 1 || call.getArguments().size() > 2) throw error(call, "Integer.parseInt expects a value and optional radix");
            usedRuntime.add("parseJavaInt");
            return "parseJavaInt(" + expressions(call.getArguments()) + ")";
        }
        if (owner.equals("java.lang.Double") && methodName.equals("parseDouble") && call.getArguments().size() == 1) {
            usedRuntime.add("parseJavaDouble");
            return "parseJavaDouble(" + expression(call.getArguments().get(0)) + ")";
        }
        if (owner.equals("java.lang.Float") && methodName.equals("parseFloat") && call.getArguments().size() == 1) {
            usedRuntime.add("parseJavaDouble");
            return "Math.fround(parseJavaDouble(" + expression(call.getArguments().get(0)) + "))";
        }
        if (owner.equals("java.lang.Long") && methodName.startsWith("parse")) throw error(call, "Java long values are not supported");
        if (receiver != null && call.getArguments().isEmpty() && methodName.equals("length") && isJavaString(receiver)) {
            return expression(receiver) + ".length";
        }
        if (receiver != null && owner.equals("java.lang.String") && methodName.equals("equals") && call.getArguments().size() == 1) {
            return "(" + expression(receiver) + " === " + expression(call.getArguments().get(0)) + ")";
        }
        if (receiver != null && methodName.equals("add") && isJavaCollection(receiver)) {
            if (call.getArguments().size() == 1) return "(" + expression(receiver) + ".push(" + expression(call.getArguments().get(0)) + "), true)";
            if (call.getArguments().size() == 2) return expression(receiver) + ".splice(" + expression(call.getArguments().get(0)) + ", 0, " + expression(call.getArguments().get(1)) + ")";
            throw error(call, "List.add expects one value or an index and value");
        }
        if (receiver != null && methodName.equals("size") && isJavaCollection(receiver)) return expression(receiver) + ".length";
        if (receiver != null && isJavaCollection(receiver)) {
            String target = expression(receiver);
            if (methodName.equals("get") && call.getArguments().size() == 1) return target + "[" + expression(call.getArguments().get(0)) + "]";
            if (methodName.equals("set") && call.getArguments().size() == 2) return target + ".splice(" + expression(call.getArguments().get(0)) + ", 1, " + expression(call.getArguments().get(1)) + ")[0]";
            if (methodName.equals("contains") && call.getArguments().size() == 1) return target + ".includes(" + expression(call.getArguments().get(0)) + ")";
            if (methodName.equals("indexOf") && call.getArguments().size() == 1) return target + ".indexOf(" + expression(call.getArguments().get(0)) + ")";
            if (methodName.equals("isEmpty") && call.getArguments().isEmpty()) return "(" + target + ".length === 0)";
            if (methodName.equals("clear") && call.getArguments().isEmpty()) return target + ".splice(0)";
            throw error(call, "Unsupported List/Collection method: " + methodName);
        }
        if (receiver != null && owner.startsWith("java.util.Map")) return mapInvocation(call, receiver, methodName);
        if (receiver != null && owner.startsWith("java.util.Set")) return setInvocation(call, receiver, methodName);
        if (receiver != null && call.getArguments().isEmpty() && recordHasAccessor(receiver, methodName)) {
            return expression(receiver) + "." + methodName;
        }
        if (receiver == null && COMPONENT_METHODS.contains(methodName) && owner.equals("javelin.ui.Component")) {
            return methodName.equals("props") ? "this.props" : "this." + methodName + "(" + expressions(call.getArguments()) + ")";
        }
        if (receiver == null && RUNTIME_NAMES.contains(methodName) && owner.equals("javelin.ui.Html")) {
            if (methodName.equals("cssModule") && (call.getArguments().size() != 2 ||
                    call.getArguments().stream().anyMatch(argument -> !(argument instanceof LiteralTree literal) || !(literal.getValue() instanceof String)))) {
                throw error(call, "cssModule requires literal module path and class name arguments");
            }
            if (methodName.equals("lazy")) return lazyInvocation(call);
            usedRuntime.add(methodName);
            return methodName + "(" + expressions(call.getArguments()) + ")";
        }
        if (receiver == null && currentClass != null && currentClass.methods.contains(methodName)) {
            String target = currentClass.staticMethods.contains(methodName) ? currentClass.name : "this";
            return target + "." + methodName + "(" + expressions(call.getArguments()) + ")";
        }
        return (receiver == null ? methodName : expression(receiver) + "." + methodName) + "(" + expressions(call.getArguments()) + ")";
    }

    private String lazyInvocation(MethodInvocationTree call) {
        if (call.getArguments().size() < 1 || call.getArguments().size() > 2 ||
                call.getArguments().stream().anyMatch(argument -> !(argument instanceof LiteralTree literal) || !(literal.getValue() instanceof String))) {
            throw error(call, "lazy requires a literal module path and optional literal export name");
        }
        String modulePath = (String) ((LiteralTree) call.getArguments().get(0)).getValue();
        if (!(modulePath.startsWith("./") || modulePath.startsWith("../") || modulePath.startsWith("/")) || modulePath.contains("\\")) {
            throw error(call, "lazy module path must be a relative or root-relative browser path");
        }
        String exportName = call.getArguments().size() == 2 ? (String) ((LiteralTree) call.getArguments().get(1)).getValue() : "default";
        usedRuntime.add("lazy");
        return "lazy(() => import(" + quote(modulePath) + ").then((module) => module[" + quote(exportName) + "]))";
    }

    private String mapOf(MethodInvocationTree call) {
        if (call.getArguments().size() % 2 != 0) throw error(call, "Map.of requires key/value pairs");
        List<String> pairs = new ArrayList<>();
        for (int i = 0; i < call.getArguments().size(); i += 2) {
            pairs.add("[" + expression(call.getArguments().get(i)) + ", " + expression(call.getArguments().get(i + 1)) + "]");
        }
        return "new Map([" + String.join(", ", pairs) + "])";
    }

    private String mapInvocation(MethodInvocationTree call, ExpressionTree receiver, String methodName) {
        String target = expression(receiver);
        if (methodName.equals("get") && call.getArguments().size() == 1) return target + ".get(" + expression(call.getArguments().get(0)) + ")";
        if (methodName.equals("containsKey") && call.getArguments().size() == 1) return target + ".has(" + expression(call.getArguments().get(0)) + ")";
        if (methodName.equals("size") && call.getArguments().isEmpty()) return target + ".size";
        if (methodName.equals("isEmpty") && call.getArguments().isEmpty()) return "(" + target + ".size === 0)";
        if (methodName.equals("clear") && call.getArguments().isEmpty()) return target + ".clear()";
        if (methodName.equals("put") && call.getArguments().size() == 2) {
            String key = expression(call.getArguments().get(0));
            String value = expression(call.getArguments().get(1));
            return "((m, k, v) => { const previous = m.get(k); m.set(k, v); return previous; })(" + target + ", " + key + ", " + value + ")";
        }
        throw error(call, "Unsupported Map method: " + methodName);
    }

    private String setInvocation(MethodInvocationTree call, ExpressionTree receiver, String methodName) {
        String target = expression(receiver);
        if (methodName.equals("contains") && call.getArguments().size() == 1) return target + ".has(" + expression(call.getArguments().get(0)) + ")";
        if (methodName.equals("size") && call.getArguments().isEmpty()) return target + ".size";
        if (methodName.equals("isEmpty") && call.getArguments().isEmpty()) return "(" + target + ".size === 0)";
        if (methodName.equals("clear") && call.getArguments().isEmpty()) return target + ".clear()";
        if (methodName.equals("add") && call.getArguments().size() == 1) {
            String value = expression(call.getArguments().get(0));
            return "((s, v) => s.has(v) ? false : (s.add(v), true))(" + target + ", " + value + ")";
        }
        throw error(call, "Unsupported Set method: " + methodName);
    }

    private boolean isJavaCollection(ExpressionTree receiver) {
        TypeMirror type = trees.getTypeMirror(TreePath.getPath(currentUnit, receiver));
        if (type == null) return false;
        String name = type.toString();
        return name.startsWith("java.util.List") || name.startsWith("java.util.ArrayList") ||
                name.startsWith("java.util.LinkedList") || name.startsWith("java.util.Collection");
    }

    private boolean isJavaCollectionLike(ExpressionTree expression) {
        String name = typeName(expression);
        return name.startsWith("java.util.List") || name.startsWith("java.util.ArrayList") ||
                name.startsWith("java.util.LinkedList") || name.startsWith("java.util.Collection") ||
                name.startsWith("java.util.Set") || name.startsWith("java.util.HashSet") || name.startsWith("java.util.LinkedHashSet");
    }

    private boolean isJavaMapLike(ExpressionTree expression) {
        String name = typeName(expression);
        return name.startsWith("java.util.Map") || name.startsWith("java.util.HashMap") || name.startsWith("java.util.LinkedHashMap");
    }

    private String typeName(Tree tree) {
        TypeMirror type = trees.getTypeMirror(TreePath.getPath(currentUnit, tree));
        if (type == null) return "";
        String name = type.toString();
        int generic = name.indexOf('<');
        return generic >= 0 ? name.substring(0, generic) : name;
    }

    private boolean isJavaString(ExpressionTree receiver) {
        TypeMirror type = trees.getTypeMirror(TreePath.getPath(currentUnit, receiver));
        return type != null && type.toString().equals("java.lang.String");
    }

    private boolean recordHasAccessor(ExpressionTree receiver, String methodName) {
        TypeMirror type = trees.getTypeMirror(TreePath.getPath(currentUnit, receiver));
        if (type == null) return false;
        String typeName = type.toString();
        int generic = typeName.indexOf('<');
        if (generic >= 0) typeName = typeName.substring(0, generic);
        int separator = typeName.lastIndexOf('.');
        String simpleName = separator >= 0 ? typeName.substring(separator + 1) : typeName;
        RecordModel record = records.get(simpleName);
        return record != null && record.fields.contains(methodName);
    }

    private String invocationOwner(MethodInvocationTree call) {
        Element element = trees.getElement(TreePath.getPath(currentUnit, call));
        if (element == null) return "";
        Element owner = element.getEnclosingElement();
        return owner instanceof TypeElement type ? type.getQualifiedName().toString() : owner.toString();
    }

    private String binary(BinaryTree value) {
        String operator = switch (value.getKind()) {
            case MULTIPLY -> "*"; case DIVIDE -> "/"; case REMAINDER -> "%"; case PLUS -> "+"; case MINUS -> "-";
            case LEFT_SHIFT -> "<<"; case RIGHT_SHIFT -> ">>"; case UNSIGNED_RIGHT_SHIFT -> ">>>";
            case LESS_THAN -> "<"; case GREATER_THAN -> ">"; case LESS_THAN_EQUAL -> "<="; case GREATER_THAN_EQUAL -> ">=";
            case EQUAL_TO -> "==="; case NOT_EQUAL_TO -> "!=="; case AND -> "&"; case XOR -> "^"; case OR -> "|";
            case CONDITIONAL_AND -> "&&"; case CONDITIONAL_OR -> "||";
            default -> throw error(value, "Unsupported binary operator: " + value.getKind());
        };
        TypeMirror resultType = trees.getTypeMirror(TreePath.getPath(currentUnit, value));
        if (resultType != null && resultType.getKind() == TypeKind.LONG) throw error(value, "Java long arithmetic is not supported");
        boolean stringConcat = value.getKind() == Tree.Kind.PLUS && resultType != null && resultType.toString().equals("java.lang.String");
        String left = expression(value.getLeftOperand());
        String right = expression(value.getRightOperand());
        if (!stringConcat && (isChar(value.getLeftOperand()) || isChar(value.getRightOperand()))) {
            usedRuntime.add("numericValue");
            if (isChar(value.getLeftOperand())) left = "numericValue(" + left + ")";
            if (isChar(value.getRightOperand())) right = "numericValue(" + right + ")";
        }
        String emitted = left + " " + operator + " " + right;
        if (resultType != null && resultType.getKind() == TypeKind.FLOAT && Set.of(Tree.Kind.MULTIPLY, Tree.Kind.DIVIDE, Tree.Kind.REMAINDER, Tree.Kind.PLUS, Tree.Kind.MINUS).contains(value.getKind())) {
            return "Math.fround(" + emitted + ")";
        }
        if (resultType != null && Set.of(TypeKind.BYTE, TypeKind.SHORT, TypeKind.INT).contains(resultType.getKind())) {
            if (value.getKind() == Tree.Kind.MULTIPLY) return "Math.imul(" + left + ", " + right + ")";
            if (Set.of(Tree.Kind.PLUS, Tree.Kind.MINUS, Tree.Kind.REMAINDER).contains(value.getKind())) return "((" + emitted + ") | 0)";
        }
        if (value.getKind() == Tree.Kind.DIVIDE) {
            if (resultType != null && Set.of(TypeKind.BYTE, TypeKind.SHORT, TypeKind.INT).contains(resultType.getKind())) return "(Math.trunc(" + emitted + ") | 0)";
        }
        return "(" + emitted + ")";
    }

    private String cast(TypeCastTree value) {
        TypeMirror castType = trees.getTypeMirror(TreePath.getPath(currentUnit, value.getType()));
        if (castType == null || !castType.getKind().isPrimitive()) return expression(value.getExpression());
        String helper = switch (castType.getKind()) {
            case BYTE -> "castByte";
            case SHORT -> "castShort";
            case CHAR -> "castChar";
            case INT -> "castInt";
            case FLOAT -> "castFloat";
            case DOUBLE -> "numericValue";
            case LONG -> throw error(value, "Java long casts are not supported");
            default -> throw error(value, "Unsupported primitive cast to " + castType);
        };
        usedRuntime.add(helper);
        return helper + "(" + expression(value.getExpression()) + ")";
    }

    private boolean isChar(ExpressionTree tree) {
        TypeMirror type = trees.getTypeMirror(TreePath.getPath(currentUnit, tree));
        return type != null && type.getKind() == TypeKind.CHAR;
    }

    private String unary(UnaryTree value) {
        if (isChar(value.getExpression())) {
            usedRuntime.add("numericValue");
            if (Set.of(Tree.Kind.UNARY_PLUS, Tree.Kind.UNARY_MINUS, Tree.Kind.BITWISE_COMPLEMENT).contains(value.getKind())) {
                String operator = value.getKind() == Tree.Kind.UNARY_PLUS ? "+" : value.getKind() == Tree.Kind.UNARY_MINUS ? "-" : "~";
                return operator + "numericValue(" + expression(value.getExpression()) + ")";
            }
            throw error(value, "Incrementing or decrementing char values is not supported yet");
        }
        String operator = switch (value.getKind()) {
            case PREFIX_INCREMENT, POSTFIX_INCREMENT -> "++"; case PREFIX_DECREMENT, POSTFIX_DECREMENT -> "--";
            case UNARY_PLUS -> "+"; case UNARY_MINUS -> "-"; case BITWISE_COMPLEMENT -> "~"; case LOGICAL_COMPLEMENT -> "!";
            default -> throw error(value, "Unsupported unary expression: " + value.getKind());
        };
        return switch (value.getKind()) {
            case POSTFIX_INCREMENT, POSTFIX_DECREMENT -> expression(value.getExpression()) + operator;
            default -> operator + expression(value.getExpression());
        };
    }

    private String compoundOperator(Tree.Kind kind) {
        return switch (kind) {
            case PLUS_ASSIGNMENT -> "+="; case MINUS_ASSIGNMENT -> "-="; case MULTIPLY_ASSIGNMENT -> "*=";
            case DIVIDE_ASSIGNMENT -> "/="; case REMAINDER_ASSIGNMENT -> "%="; case AND_ASSIGNMENT -> "&=";
            case OR_ASSIGNMENT -> "|="; case XOR_ASSIGNMENT -> "^="; case LEFT_SHIFT_ASSIGNMENT -> "<<=";
            case RIGHT_SHIFT_ASSIGNMENT -> ">>="; case UNSIGNED_RIGHT_SHIFT_ASSIGNMENT -> ">>>=";
            default -> throw error(null, "Unsupported assignment operator: " + kind);
        };
    }

    private String expressions(List<? extends ExpressionTree> values) {
        return values.stream().map(this::expression).collect(Collectors.joining(", "));
    }

    private String literal(Object value) {
        if (value == null) return "null";
        if (value instanceof String || value instanceof Character) return quote(value.toString());
        if (value instanceof Long) throw error(null, "Java long literals are not supported");
        return value.toString();
    }

    private String annotationString(ModifiersTree modifiers, String simpleName) {
        return modifiers.getAnnotations().stream().filter(annotation -> {
                    Element element = trees.getElement(TreePath.getPath(currentUnit, annotation.getAnnotationType()));
                    return element instanceof TypeElement type && type.getQualifiedName().contentEquals("javelin.ui." + simpleName);
                })
                .findFirst().map(annotation -> {
                    if (annotation.getArguments().size() != 1) throw error(annotation, "@" + simpleName + " requires one argument");
                    ExpressionTree argument = annotation.getArguments().get(0);
                    if (argument instanceof AssignmentTree assignment) argument = assignment.getExpression();
                    if (!(argument instanceof LiteralTree literal) || !(literal.getValue() instanceof String value)) {
                        throw error(annotation, "@" + simpleName + " requires a string literal");
                    }
                    return value;
                }).orElse(null);
    }

    private boolean hasAnnotation(ModifiersTree modifiers, String simpleName) {
        return modifiers.getAnnotations().stream().anyMatch(annotation -> {
            Element element = trees.getElement(TreePath.getPath(currentUnit, annotation.getAnnotationType()));
            return element instanceof TypeElement type && type.getQualifiedName().contentEquals("javelin.ui." + simpleName);
        });
    }

    private String marker(CompilationUnitTree unit, Tree tree) {
        long position = positions.getStartPosition(unit, tree);
        long line = position < 0 ? 1 : unit.getLineMap().getLineNumber(position);
        String file = Path.of(unit.getSourceFile().toUri()).toString();
        return "//#javelin-source " + Base64.getUrlEncoder().withoutPadding().encodeToString(file.getBytes(StandardCharsets.UTF_8)) + ":" + line;
    }

    private void sourceMarker(CompilationUnitTree unit, Tree tree) {
        // Marker generation is centralized in marker(); this method documents the mapping point.
    }

    private RuntimeException error(Tree tree, String message) {
        if (tree == null || currentUnit == null) return new IllegalArgumentException(message);
        long position = positions.getStartPosition(currentUnit, tree);
        long line = position < 0 ? 1 : currentUnit.getLineMap().getLineNumber(position);
        long column = position < 0 ? 1 : currentUnit.getLineMap().getColumnNumber(position);
        return new IllegalArgumentException(Path.of(currentUnit.getSourceFile().toUri()) + ":" + line + ":" + column + ": " + message);
    }

    private static String quote(String value) {
        StringBuilder output = new StringBuilder("\"");
        for (int index = 0; index < value.length(); index++) {
            char character = value.charAt(index);
            switch (character) {
                case '\\' -> output.append("\\\\");
                case '"' -> output.append("\\\"");
                case '\n' -> output.append("\\n");
                case '\r' -> output.append("\\r");
                case '\t' -> output.append("\\t");
                case '\b' -> output.append("\\b");
                case '\f' -> output.append("\\f");
                default -> {
                    if (character < 0x20 || character == '\u2028' || character == '\u2029') output.append(String.format("\\u%04x", (int) character));
                    else output.append(character);
                }
            }
        }
        return output.append('"').toString();
    }

    private record RecordModel(String name, List<String> fields, CompilationUnitTree unit, ClassTree tree) {}
    private record ClassModel(String name, String qualifiedName, String superName, String selector, boolean lazy, Set<String> fields, Set<String> staticFields, Set<String> methods, Set<String> staticMethods,
                              CompilationUnitTree unit, ClassTree tree) {}
}
